### ISSUE TITLE
Revisión del correcto funcionamiento en WIndows

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-lib#108]

**Comment by carlosalvarezrivas** [comment]
Siguiendo las instrucciones preparadas en github de Alastria, los dos pirmeros pasos que son clonar los repositorios se realizan si problemas.
Pero al llegar a la tercera que es instalarla:
Then, you must go to the alastria-identity-example's folder and run the following command
`npm install --save github:alastria/alastria-identity-lib.git#develop`

Se produce los siguientes errores:

**Error 1:**

`gyp ERR! build error`
`gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:315:20)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`
`gyp ERR! System Windows_NT 10.0.18363`
`gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`
`gyp ERR! cwd C:\Users\carlos\Documents\Proyectos\blockchain\alastria-identity-example\node_modules\keythereum\node_modules\keccak`
`gyp ERR! node -v v12.18.2`
`gyp ERR! node-gyp -v v5.1.0`
`gyp ERR! not ok`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! keccak@1.4.0 rebuild: node-gyp rebuild`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the keccak@1.4.0 rebuild script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\carlos\AppData\Roaming\npm-cache\_logs\2020-08-18T14_59_22_273Z-debug.log`
`"Keccak bindings compilation fail. Pure JS implementation will be used."`

**Error 2:**

`gyp ERR! build error`
`gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (C:\Users\carlos\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:315:20)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`
`gyp ERR! System Windows_NT 10.0.18363`
`gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\carlos\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`
`gyp ERR! cwd C:\Users\carlos\Documents\Proyectos\blockchain\alastria-identity-example\node_modules\keythereum\node_modules\secp256k1`
`gyp ERR! node -v v12.18.2`
`gyp ERR! node-gyp -v v5.1.0`
`gyp ERR! not ok`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! secp256k1@3.5.0 rebuild: node-gyp rebuild`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the secp256k1@3.5.0 rebuild script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\carlos\AppData\Roaming\npm-cache\_logs\2020-08-20T16_40_21_732Z-debug.log`
`"Secp256k1 bindings compilation fail. Pure JS implementation will be used."`

**Error 3:**

  `C:\Users\carlos\Documents\Proyectos\blockchain\alastria-identity-example\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'`
`gyp ERR! build error`
`gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:315:20)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`
`gyp ERR! System Windows_NT 10.0.18363`
`gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`
`gyp ERR! cwd C:\Users\carlos\Documents\Proyectos\blockchain\alastria-identity-example\node_modules\scrypt`
`gyp ERR! node -v v12.18.2`
`gyp ERR! node-gyp -v v5.1.0`
`gyp ERR! not ok`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! scrypt@6.0.3 install: node-gyp rebuild`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the scrypt@6.0.3 install script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\carlos\AppData\Roaming\npm-cache\_logs\2020-08-18T14_59_32_988Z-debug.log`



Parece ser que está relacionado con "windows-build-tools", pero no he sido capaza de solucionarlo

**Comment by VictorNS69** [comment]
@carlosalvarezrivas entonces este error sigue presente? No se ha podido solucionar, no?

**Comment by carlosalvarezrivas** [comment]
Correcto, sigue el error. Yo de vez en cuando le echo un poco de tiempo para intentar encontrar la solución pero a día de hoy no la he encontrado.

**Comment by VictorNS69** [comment]
> Correcto, sigue el error. Yo de vez en cuando le echo un poco de tiempo para intentar encontrar la solución pero a día de hoy no la he encontrado.

Ok, sin problema. Muevo de nuevo a "in progress" :smile:

**Comment by VictorNS69** [comment]
Comenta el equipo que es posible que sea por la versión de Node que se está utilizando. Podrías probar con Node 10 ?

**Comment by carlosalvarezrivas** [comment]
He instalado la versión de node 10.23.0 y me da otro error
![image](https://user-images.githubusercontent.com/6537309/101492188-8e2cb080-395c-11eb-994d-45e769c078dd.png)

**Comment by VictorNS69** [comment]
Hmm.. ese error parece que es por que no puede crear la carpeta "node_modules". Puede ser algo de permisos?
